spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hsj.com:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: super_mybatis
    password: 323ba860e23d4982a9a4c978c8752eaa

super-mybatis:
  global-setting:
    database-setting:
      show-sql: true